{
 "title": "WireGuard",
 "tags": [ "wireguard" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(wireguard_sent_bytes_total[1m])",
     "legendFormat": "↑ {{interface}} ({{remote_ip}})"
    },
    {
     "expr": "irate(wireguard_received_bytes_total[1m])",
     "legendFormat": "↓ {{interface}} ({{remote_ip}})"
    }
   ]
  },
  {
   "title": "Total Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(wireguard_sent_bytes_total)"
    }
   ]
  },
  {
   "title": "Total Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(wireguard_received_bytes_total)"
    }
   ]
  },
  {
   "title": "Last Handshake",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(wireguard_latest_handshake_delay_seconds)"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "count(wireguard_latest_handshake_seconds)"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "wireguard_latest_handshake_delay_seconds"
    }
   ]
  }
 ]
}